---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggchalkboard

<!-- badges: start -->
<!-- badges: end -->

The goal of ggchalkboard is to ...

## Installation

You can install the released version of ggchalkboard from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ggchalkboard")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("EvaMaeRey/ggchalkboard")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ggchalkboard)
## basic example code

library(ggplot2)

geoms_chalk()
ggplot(cars) +
  aes(speed, dist) +
  geom_point() +
  theme_chalkboard()


library(ggplot2)
geoms_chalk()
ggplot(cars) +
 aes(speed, dist) +
 geom_point() +
 theme_chalkboard_slate()
```
# How?

```{r}
the_code <- readLines("R/theme_chalkboard.R")
```


```{r, code = the_code}


```
